version: '3.9'

services:
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .mongo.env
    command: [ --auth ]
  backend:
    image: oxxydde/url-shortener-be:latest
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - .env
      - .mongo.env